"""add_error_book_tables

Revision ID: add_error_book_tables
Revises: 5b2fedd12211
Create Date: 2025-01-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_error_book_tables'
down_revision: Union[str, None] = '5b2fedd12211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建错题表
    op.create_table('error_questions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='更新时间'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('subject', sa.String(length=50), nullable=False, comment='学科'),
    sa.Column('question_content', sa.Text(), nullable=False, comment='题目内容'),
    sa.Column('student_answer', sa.Text(), nullable=True, comment='学生答案'),
    sa.Column('correct_answer', sa.Text(), nullable=True, comment='正确答案'),
    sa.Column('error_type', sa.String(length=100), nullable=False, comment='错误类型'),
    sa.Column('error_subcategory', sa.String(length=100), nullable=True, comment='错误子分类'),
    sa.Column('knowledge_points', sa.JSON(), nullable=True, comment='关联知识点'),
    sa.Column('difficulty_level', sa.Integer(), nullable=True, comment='难度等级(1-5)'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源类型'),
    sa.Column('source_id', sa.String(length=36), nullable=True, comment='来源ID'),
    sa.Column('mastery_status', sa.String(length=20), nullable=False, comment='掌握状态'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='复习次数'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='答对次数'),
    sa.Column('last_review_at', sa.DateTime(), nullable=True, comment='最后复习时间'),
    sa.Column('next_review_at', sa.DateTime(), nullable=True, comment='下次复习时间'),
    sa.Column('is_starred', sa.Boolean(), nullable=True, comment='是否标星'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='自定义标签'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    
    # 创建索引
    op.create_index(op.f('ix_error_questions_user_id'), 'error_questions', ['user_id'], unique=False)
    op.create_index(op.f('ix_error_questions_subject'), 'error_questions', ['subject'], unique=False)
    op.create_index(op.f('ix_error_questions_mastery_status'), 'error_questions', ['mastery_status'], unique=False)
    op.create_index(op.f('ix_error_questions_next_review_at'), 'error_questions', ['next_review_at'], unique=False)
    
    # 创建复习记录表
    op.create_table('review_records',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='更新时间'),
    sa.Column('error_question_id', sa.String(length=36), nullable=False, comment='错题ID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('review_result', sa.String(length=20), nullable=False, comment='复习结果'),
    sa.Column('score', sa.Integer(), nullable=True, comment='得分(0-100)'),
    sa.Column('time_spent', sa.Integer(), nullable=True, comment='用时(秒)'),
    sa.Column('student_answer', sa.Text(), nullable=True, comment='本次学生答案'),
    sa.Column('notes', sa.Text(), nullable=True, comment='复习笔记'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False, comment='复习时间'),
    sa.Column('next_review_at', sa.DateTime(), nullable=True, comment='下次复习时间'),
    sa.ForeignKeyConstraint(['error_question_id'], ['error_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    
    # 创建索引
    op.create_index(op.f('ix_review_records_error_question_id'), 'review_records', ['error_question_id'], unique=False)
    op.create_index(op.f('ix_review_records_user_id'), 'review_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_records_reviewed_at'), 'review_records', ['reviewed_at'], unique=False)
    
    # 创建错题分类表
    op.create_table('error_classifications',
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.String(length=50), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.String(length=50), nullable=False, comment='更新时间'),
    sa.Column('error_question_id', sa.String(length=36), nullable=False, comment='错题ID'),
    sa.Column('category', sa.String(length=100), nullable=False, comment='主分类'),
    sa.Column('subcategory', sa.String(length=100), nullable=True, comment='子分类'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='置信度(0.0-1.0)'),
    sa.Column('classification_details', sa.JSON(), nullable=True, comment='分类详细信息'),
    sa.Column('classified_at', sa.DateTime(), nullable=False, comment='分类时间'),
    sa.ForeignKeyConstraint(['error_question_id'], ['error_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    
    # 创建索引
    op.create_index(op.f('ix_error_classifications_error_question_id'), 'error_classifications', ['error_question_id'], unique=False)
    op.create_index(op.f('ix_error_classifications_category'), 'error_classifications', ['category'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除错题分类表
    op.drop_index(op.f('ix_error_classifications_category'), table_name='error_classifications')
    op.drop_index(op.f('ix_error_classifications_error_question_id'), table_name='error_classifications')
    op.drop_table('error_classifications')
    
    # 删除复习记录表
    op.drop_index(op.f('ix_review_records_reviewed_at'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_user_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_error_question_id'), table_name='review_records')
    op.drop_table('review_records')
    
    # 删除错题表
    op.drop_index(op.f('ix_error_questions_next_review_at'), table_name='error_questions')
    op.drop_index(op.f('ix_error_questions_mastery_status'), table_name='error_questions')
    op.drop_index(op.f('ix_error_questions_subject'), table_name='error_questions')
    op.drop_index(op.f('ix_error_questions_user_id'), table_name='error_questions')
    op.drop_table('error_questions')
    
    # ### end Alembic commands ###