"""review sector

Revision ID: fb4caaaf21e5
Revises: 20251104_formula_cache
Create Date: 2025-11-08 17:14:28.540461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb4caaaf21e5"
down_revision: Union[str, Sequence[str], None] = "20251104_formula_cache"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 只保留 mistake_review_sessions 表的创建，其他变更已注释
    op.create_table(
        "mistake_review_sessions",
        sa.Column("mistake_id", UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("current_stage", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=True),
        sa.Column("id", UUID(as_uuid=True), nullable=False, comment="主键ID"),
        sa.Column(
            "created_at", sa.String(length=50), nullable=False, comment="创建时间"
        ),
        sa.Column(
            "updated_at", sa.String(length=50), nullable=False, comment="更新时间"
        ),
        sa.ForeignKeyConstraint(
            ["mistake_id"],
            ["mistake_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_mistake_review_sessions_status"),
        "mistake_review_sessions",
        ["status"],
        unique=False,
    )

    # 以下 alter_column 操作已注释，因为它们在 SQLite 中不兼容
    # 且不是本次迁移的核心内容
    # op.alter_column('homework', 'creator_id',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    op.alter_column(
        "homework_images",
        "submission_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_reviews",
        "submission_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_reviews",
        "reviewer_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "homework_submissions",
        "homework_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_submissions",
        "student_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_graphs",
        "created_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_mastery",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_nodes",
        "parent_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_relations",
        "from_node_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_relations",
        "to_node_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "learning_paths",
        "created_by",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.add_column(
        "mistake_records",
        sa.Column(
            "source_question_id",
            sa.String(length=36),
            nullable=True,
            comment="关联的Question ID",
        ),
    )
    op.add_column(
        "mistake_records",
        sa.Column("student_answer", sa.Text(), nullable=True, comment="学生答案"),
    )
    op.add_column(
        "mistake_records",
        sa.Column("correct_answer", sa.Text(), nullable=True, comment="正确答案"),
    )
    op.create_index(
        op.f("ix_mistake_records_source_question_id"),
        "mistake_records",
        ["source_question_id"],
        unique=False,
    )
    op.alter_column(
        "review_schedule",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "review_schedule",
        "mistake_record_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "study_sessions",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_learning_paths",
        "user_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_learning_paths",
        "learning_path_id",
        existing_type=sa.NUMERIC(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_learning_paths",
        "learning_path_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_learning_paths",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "study_sessions",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "review_schedule",
        "mistake_record_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "review_schedule",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_mistake_records_source_question_id"), table_name="mistake_records"
    )
    op.drop_column("mistake_records", "correct_answer")
    op.drop_column("mistake_records", "student_answer")
    op.drop_column("mistake_records", "source_question_id")
    op.alter_column(
        "learning_paths",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_relations",
        "to_node_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_relations",
        "from_node_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_nodes",
        "parent_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_mastery",
        "user_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_graphs",
        "created_by",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "homework_submissions",
        "student_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_submissions",
        "homework_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_reviews",
        "reviewer_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.alter_column(
        "homework_reviews",
        "submission_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework_images",
        "submission_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "homework",
        "creator_id",
        existing_type=sa.UUID(),
        type_=sa.NUMERIC(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_mistake_review_sessions_status"), table_name="mistake_review_sessions"
    )
    op.drop_table("mistake_review_sessions")
    # ### end Alembic commands ###
