-- 创建用户 15662660599
-- 密码: User7kB3Qm (包含大写、小写和数字)
-- 密码哈希使用 bcrypt，需在服务器上生成

-- 先检查用户是否已存在
SELECT id, phone, name, is_active FROM users WHERE phone = '15662660599' AND deleted_at IS NULL;

-- 如果不存在，执行以下插入（需要先在服务器上生成密码哈希）
-- INSERT INTO users (
--     id,
--     phone,
--     password_hash,
--     name,
--     nickname,
--     role,
--     is_active,
--     is_verified,
--     login_count,
--     created_at,
--     updated_at
-- ) VALUES (
--     gen_random_uuid(),
--     '15662660599',
--     '<PASSWORD_HASH>',  -- 需要用 bcrypt 生成
--     '李国马',
--     '李国马',
--     'student',
--     true,
--     true,
--     0,
--     NOW(),
--     NOW()
-- );
